//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AmazonCrawlerModel", "FK_Book_Author", "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AmazonCrawler.Author), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AmazonCrawler.Book), true)]
[assembly: EdmRelationshipAttribute("AmazonCrawlerModel", "FK_Ranking_Author", "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AmazonCrawler.Author), "Ranking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AmazonCrawler.Ranking), true)]
[assembly: EdmRelationshipAttribute("AmazonCrawlerModel", "FK_Ranking_Book", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AmazonCrawler.Book), "Ranking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AmazonCrawler.Ranking), true)]
[assembly: EdmRelationshipAttribute("AmazonCrawlerModel", "FK_Review_Book", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AmazonCrawler.Book), "Review", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AmazonCrawler.Review), true)]
[assembly: EdmRelationshipAttribute("AmazonCrawlerModel", "FK_Review_Reviewer", "Reviewer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AmazonCrawler.Reviewer), "Review", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AmazonCrawler.Review), true)]
[assembly: EdmRelationshipAttribute("AmazonCrawlerModel", "FK_ReviewerBadge_Reviewer", "Reviewer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AmazonCrawler.Reviewer), "ReviewerBadge", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AmazonCrawler.ReviewerBadge), true)]

#endregion

namespace AmazonCrawler
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AmazonCrawlerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AmazonCrawlerEntities object using the connection string found in the 'AmazonCrawlerEntities' section of the application configuration file.
        /// </summary>
        public AmazonCrawlerEntities() : base("name=AmazonCrawlerEntities", "AmazonCrawlerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AmazonCrawlerEntities object.
        /// </summary>
        public AmazonCrawlerEntities(string connectionString) : base(connectionString, "AmazonCrawlerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AmazonCrawlerEntities object.
        /// </summary>
        public AmazonCrawlerEntities(EntityConnection connection) : base(connection, "AmazonCrawlerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Author> Authors
        {
            get
            {
                if ((_Authors == null))
                {
                    _Authors = base.CreateObjectSet<Author>("Authors");
                }
                return _Authors;
            }
        }
        private ObjectSet<Author> _Authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Book> Books
        {
            get
            {
                if ((_Books == null))
                {
                    _Books = base.CreateObjectSet<Book>("Books");
                }
                return _Books;
            }
        }
        private ObjectSet<Book> _Books;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ranking> Rankings
        {
            get
            {
                if ((_Rankings == null))
                {
                    _Rankings = base.CreateObjectSet<Ranking>("Rankings");
                }
                return _Rankings;
            }
        }
        private ObjectSet<Ranking> _Rankings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Review> Reviews
        {
            get
            {
                if ((_Reviews == null))
                {
                    _Reviews = base.CreateObjectSet<Review>("Reviews");
                }
                return _Reviews;
            }
        }
        private ObjectSet<Review> _Reviews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reviewer> Reviewers
        {
            get
            {
                if ((_Reviewers == null))
                {
                    _Reviewers = base.CreateObjectSet<Reviewer>("Reviewers");
                }
                return _Reviewers;
            }
        }
        private ObjectSet<Reviewer> _Reviewers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReviewerBadge> ReviewerBadges
        {
            get
            {
                if ((_ReviewerBadges == null))
                {
                    _ReviewerBadges = base.CreateObjectSet<ReviewerBadge>("ReviewerBadges");
                }
                return _ReviewerBadges;
            }
        }
        private ObjectSet<ReviewerBadge> _ReviewerBadges;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthors(Author author)
        {
            base.AddObject("Authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Books EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBooks(Book book)
        {
            base.AddObject("Books", book);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rankings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRankings(Ranking ranking)
        {
            base.AddObject("Rankings", ranking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reviewers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviewers(Reviewer reviewer)
        {
            base.AddObject("Reviewers", reviewer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReviewerBadges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviewerBadges(ReviewerBadge reviewerBadge)
        {
            base.AddObject("ReviewerBadges", reviewerBadge);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmazonCrawlerModel", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Author CreateAuthor(global::System.String id)
        {
            Author author = new Author();
            author.id = id;
            return author;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detailPageURL
        {
            get
            {
                return _detailPageURL;
            }
            set
            {
                OndetailPageURLChanging(value);
                ReportPropertyChanging("detailPageURL");
                _detailPageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detailPageURL");
                OndetailPageURLChanged();
            }
        }
        private global::System.String _detailPageURL;
        partial void OndetailPageURLChanging(global::System.String value);
        partial void OndetailPageURLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Book_Author", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("AmazonCrawlerModel.FK_Book_Author", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("AmazonCrawlerModel.FK_Book_Author", "Book", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Ranking_Author", "Ranking")]
        public EntityCollection<Ranking> Rankings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ranking>("AmazonCrawlerModel.FK_Ranking_Author", "Ranking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ranking>("AmazonCrawlerModel.FK_Ranking_Author", "Ranking", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmazonCrawlerModel", Name="Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Book : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="iSBN">Initial value of the ISBN property.</param>
        public static Book CreateBook(global::System.String iSBN)
        {
            Book book = new Book();
            book.ISBN = iSBN;
            return book;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                if (_ISBN != value)
                {
                    OnISBNChanging(value);
                    ReportPropertyChanging("ISBN");
                    _ISBN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ISBN");
                    OnISBNChanged();
                }
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authorId
        {
            get
            {
                return _authorId;
            }
            set
            {
                OnauthorIdChanging(value);
                ReportPropertyChanging("authorId");
                _authorId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("authorId");
                OnauthorIdChanged();
            }
        }
        private global::System.String _authorId;
        partial void OnauthorIdChanging(global::System.String value);
        partial void OnauthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String language
        {
            get
            {
                return _language;
            }
            set
            {
                OnlanguageChanging(value);
                ReportPropertyChanging("language");
                _language = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("language");
                OnlanguageChanged();
            }
        }
        private global::System.String _language;
        partial void OnlanguageChanging(global::System.String value);
        partial void OnlanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> statsCollectedAt
        {
            get
            {
                return _statsCollectedAt;
            }
            set
            {
                OnstatsCollectedAtChanging(value);
                ReportPropertyChanging("statsCollectedAt");
                _statsCollectedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("statsCollectedAt");
                OnstatsCollectedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _statsCollectedAt;
        partial void OnstatsCollectedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnstatsCollectedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> avgCustomerReview
        {
            get
            {
                return _avgCustomerReview;
            }
            set
            {
                OnavgCustomerReviewChanging(value);
                ReportPropertyChanging("avgCustomerReview");
                _avgCustomerReview = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avgCustomerReview");
                OnavgCustomerReviewChanged();
            }
        }
        private Nullable<global::System.Decimal> _avgCustomerReview;
        partial void OnavgCustomerReviewChanging(Nullable<global::System.Decimal> value);
        partial void OnavgCustomerReviewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numFiveStarRatings
        {
            get
            {
                return _numFiveStarRatings;
            }
            set
            {
                OnnumFiveStarRatingsChanging(value);
                ReportPropertyChanging("numFiveStarRatings");
                _numFiveStarRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numFiveStarRatings");
                OnnumFiveStarRatingsChanged();
            }
        }
        private Nullable<global::System.Int32> _numFiveStarRatings;
        partial void OnnumFiveStarRatingsChanging(Nullable<global::System.Int32> value);
        partial void OnnumFiveStarRatingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numFourStarRatings
        {
            get
            {
                return _numFourStarRatings;
            }
            set
            {
                OnnumFourStarRatingsChanging(value);
                ReportPropertyChanging("numFourStarRatings");
                _numFourStarRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numFourStarRatings");
                OnnumFourStarRatingsChanged();
            }
        }
        private Nullable<global::System.Int32> _numFourStarRatings;
        partial void OnnumFourStarRatingsChanging(Nullable<global::System.Int32> value);
        partial void OnnumFourStarRatingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numThreeStarRatings
        {
            get
            {
                return _numThreeStarRatings;
            }
            set
            {
                OnnumThreeStarRatingsChanging(value);
                ReportPropertyChanging("numThreeStarRatings");
                _numThreeStarRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numThreeStarRatings");
                OnnumThreeStarRatingsChanged();
            }
        }
        private Nullable<global::System.Int32> _numThreeStarRatings;
        partial void OnnumThreeStarRatingsChanging(Nullable<global::System.Int32> value);
        partial void OnnumThreeStarRatingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numTwoStarRatings
        {
            get
            {
                return _numTwoStarRatings;
            }
            set
            {
                OnnumTwoStarRatingsChanging(value);
                ReportPropertyChanging("numTwoStarRatings");
                _numTwoStarRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numTwoStarRatings");
                OnnumTwoStarRatingsChanged();
            }
        }
        private Nullable<global::System.Int32> _numTwoStarRatings;
        partial void OnnumTwoStarRatingsChanging(Nullable<global::System.Int32> value);
        partial void OnnumTwoStarRatingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numOneStarRatings
        {
            get
            {
                return _numOneStarRatings;
            }
            set
            {
                OnnumOneStarRatingsChanging(value);
                ReportPropertyChanging("numOneStarRatings");
                _numOneStarRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numOneStarRatings");
                OnnumOneStarRatingsChanged();
            }
        }
        private Nullable<global::System.Int32> _numOneStarRatings;
        partial void OnnumOneStarRatingsChanging(Nullable<global::System.Int32> value);
        partial void OnnumOneStarRatingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> salesRank
        {
            get
            {
                return _salesRank;
            }
            set
            {
                OnsalesRankChanging(value);
                ReportPropertyChanging("salesRank");
                _salesRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salesRank");
                OnsalesRankChanged();
            }
        }
        private Nullable<global::System.Int32> _salesRank;
        partial void OnsalesRankChanging(Nullable<global::System.Int32> value);
        partial void OnsalesRankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pages
        {
            get
            {
                return _pages;
            }
            set
            {
                OnpagesChanging(value);
                ReportPropertyChanging("pages");
                _pages = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pages");
                OnpagesChanged();
            }
        }
        private Nullable<global::System.Int32> _pages;
        partial void OnpagesChanging(Nullable<global::System.Int32> value);
        partial void OnpagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publisher
        {
            get
            {
                return _publisher;
            }
            set
            {
                OnpublisherChanging(value);
                ReportPropertyChanging("publisher");
                _publisher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("publisher");
                OnpublisherChanged();
            }
        }
        private global::System.String _publisher;
        partial void OnpublisherChanging(global::System.String value);
        partial void OnpublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> publicationDate
        {
            get
            {
                return _publicationDate;
            }
            set
            {
                OnpublicationDateChanging(value);
                ReportPropertyChanging("publicationDate");
                _publicationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("publicationDate");
                OnpublicationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _publicationDate;
        partial void OnpublicationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnpublicationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String readingLevel
        {
            get
            {
                return _readingLevel;
            }
            set
            {
                OnreadingLevelChanging(value);
                ReportPropertyChanging("readingLevel");
                _readingLevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("readingLevel");
                OnreadingLevelChanged();
            }
        }
        private global::System.String _readingLevel;
        partial void OnreadingLevelChanging(global::System.String value);
        partial void OnreadingLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> fmtKindle
        {
            get
            {
                return _fmtKindle;
            }
            set
            {
                OnfmtKindleChanging(value);
                ReportPropertyChanging("fmtKindle");
                _fmtKindle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fmtKindle");
                OnfmtKindleChanged();
            }
        }
        private Nullable<global::System.Boolean> _fmtKindle;
        partial void OnfmtKindleChanging(Nullable<global::System.Boolean> value);
        partial void OnfmtKindleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> fmtHardcover
        {
            get
            {
                return _fmtHardcover;
            }
            set
            {
                OnfmtHardcoverChanging(value);
                ReportPropertyChanging("fmtHardcover");
                _fmtHardcover = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fmtHardcover");
                OnfmtHardcoverChanged();
            }
        }
        private Nullable<global::System.Boolean> _fmtHardcover;
        partial void OnfmtHardcoverChanging(Nullable<global::System.Boolean> value);
        partial void OnfmtHardcoverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> fmtPaperback
        {
            get
            {
                return _fmtPaperback;
            }
            set
            {
                OnfmtPaperbackChanging(value);
                ReportPropertyChanging("fmtPaperback");
                _fmtPaperback = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fmtPaperback");
                OnfmtPaperbackChanged();
            }
        }
        private Nullable<global::System.Boolean> _fmtPaperback;
        partial void OnfmtPaperbackChanging(Nullable<global::System.Boolean> value);
        partial void OnfmtPaperbackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> fmtAudio
        {
            get
            {
                return _fmtAudio;
            }
            set
            {
                OnfmtAudioChanging(value);
                ReportPropertyChanging("fmtAudio");
                _fmtAudio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fmtAudio");
                OnfmtAudioChanged();
            }
        }
        private Nullable<global::System.Boolean> _fmtAudio;
        partial void OnfmtAudioChanging(Nullable<global::System.Boolean> value);
        partial void OnfmtAudioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> fmtUnknownBinding
        {
            get
            {
                return _fmtUnknownBinding;
            }
            set
            {
                OnfmtUnknownBindingChanging(value);
                ReportPropertyChanging("fmtUnknownBinding");
                _fmtUnknownBinding = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fmtUnknownBinding");
                OnfmtUnknownBindingChanged();
            }
        }
        private Nullable<global::System.Boolean> _fmtUnknownBinding;
        partial void OnfmtUnknownBindingChanging(Nullable<global::System.Boolean> value);
        partial void OnfmtUnknownBindingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detailPageURL
        {
            get
            {
                return _detailPageURL;
            }
            set
            {
                OndetailPageURLChanging(value);
                ReportPropertyChanging("detailPageURL");
                _detailPageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detailPageURL");
                OndetailPageURLChanged();
            }
        }
        private global::System.String _detailPageURL;
        partial void OndetailPageURLChanging(global::System.String value);
        partial void OndetailPageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewPageURL
        {
            get
            {
                return _reviewPageURL;
            }
            set
            {
                OnreviewPageURLChanging(value);
                ReportPropertyChanging("reviewPageURL");
                _reviewPageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewPageURL");
                OnreviewPageURLChanged();
            }
        }
        private global::System.String _reviewPageURL;
        partial void OnreviewPageURLChanging(global::System.String value);
        partial void OnreviewPageURLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Book_Author", "Author")]
        public Author Author
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("AmazonCrawlerModel.FK_Book_Author", "Author").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("AmazonCrawlerModel.FK_Book_Author", "Author").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Author> AuthorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("AmazonCrawlerModel.FK_Book_Author", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Author>("AmazonCrawlerModel.FK_Book_Author", "Author", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Ranking_Book", "Ranking")]
        public EntityCollection<Ranking> Rankings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ranking>("AmazonCrawlerModel.FK_Ranking_Book", "Ranking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ranking>("AmazonCrawlerModel.FK_Ranking_Book", "Ranking", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Review_Book", "Review")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("AmazonCrawlerModel.FK_Review_Book", "Review");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("AmazonCrawlerModel.FK_Review_Book", "Review", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmazonCrawlerModel", Name="Ranking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ranking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ranking object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Ranking CreateRanking(global::System.Int32 id)
        {
            Ranking ranking = new Ranking();
            ranking.id = id;
            return ranking;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authorId
        {
            get
            {
                return _authorId;
            }
            set
            {
                OnauthorIdChanging(value);
                ReportPropertyChanging("authorId");
                _authorId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("authorId");
                OnauthorIdChanged();
            }
        }
        private global::System.String _authorId;
        partial void OnauthorIdChanging(global::System.String value);
        partial void OnauthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> statsCollectedAt
        {
            get
            {
                return _statsCollectedAt;
            }
            set
            {
                OnstatsCollectedAtChanging(value);
                ReportPropertyChanging("statsCollectedAt");
                _statsCollectedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("statsCollectedAt");
                OnstatsCollectedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _statsCollectedAt;
        partial void OnstatsCollectedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnstatsCollectedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rankString
        {
            get
            {
                return _rankString;
            }
            set
            {
                OnrankStringChanging(value);
                ReportPropertyChanging("rankString");
                _rankString = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rankString");
                OnrankStringChanged();
            }
        }
        private global::System.String _rankString;
        partial void OnrankStringChanging(global::System.String value);
        partial void OnrankStringChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Ranking_Author", "Author")]
        public Author Author
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("AmazonCrawlerModel.FK_Ranking_Author", "Author").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("AmazonCrawlerModel.FK_Ranking_Author", "Author").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Author> AuthorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("AmazonCrawlerModel.FK_Ranking_Author", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Author>("AmazonCrawlerModel.FK_Ranking_Author", "Author", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Ranking_Book", "Book")]
        public Book Book
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("AmazonCrawlerModel.FK_Ranking_Book", "Book").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("AmazonCrawlerModel.FK_Ranking_Book", "Book").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Book> BookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("AmazonCrawlerModel.FK_Ranking_Book", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Book>("AmazonCrawlerModel.FK_Ranking_Book", "Book", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmazonCrawlerModel", Name="Review")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Review : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Review CreateReview(global::System.String id)
        {
            Review review = new Review();
            review.id = id;
            return review;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewerId
        {
            get
            {
                return _reviewerId;
            }
            set
            {
                OnreviewerIdChanging(value);
                ReportPropertyChanging("reviewerId");
                _reviewerId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewerId");
                OnreviewerIdChanged();
            }
        }
        private global::System.String _reviewerId;
        partial void OnreviewerIdChanging(global::System.String value);
        partial void OnreviewerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewerName
        {
            get
            {
                return _reviewerName;
            }
            set
            {
                OnreviewerNameChanging(value);
                ReportPropertyChanging("reviewerName");
                _reviewerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewerName");
                OnreviewerNameChanged();
            }
        }
        private global::System.String _reviewerName;
        partial void OnreviewerNameChanging(global::System.String value);
        partial void OnreviewerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> publishedDate
        {
            get
            {
                return _publishedDate;
            }
            set
            {
                OnpublishedDateChanging(value);
                ReportPropertyChanging("publishedDate");
                _publishedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("publishedDate");
                OnpublishedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _publishedDate;
        partial void OnpublishedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnpublishedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> starRating
        {
            get
            {
                return _starRating;
            }
            set
            {
                OnstarRatingChanging(value);
                ReportPropertyChanging("starRating");
                _starRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("starRating");
                OnstarRatingChanged();
            }
        }
        private Nullable<global::System.Int16> _starRating;
        partial void OnstarRatingChanging(Nullable<global::System.Int16> value);
        partial void OnstarRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewTitle
        {
            get
            {
                return _reviewTitle;
            }
            set
            {
                OnreviewTitleChanging(value);
                ReportPropertyChanging("reviewTitle");
                _reviewTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewTitle");
                OnreviewTitleChanged();
            }
        }
        private global::System.String _reviewTitle;
        partial void OnreviewTitleChanging(global::System.String value);
        partial void OnreviewTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewContent
        {
            get
            {
                return _reviewContent;
            }
            set
            {
                OnreviewContentChanging(value);
                ReportPropertyChanging("reviewContent");
                _reviewContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewContent");
                OnreviewContentChanged();
            }
        }
        private global::System.String _reviewContent;
        partial void OnreviewContentChanging(global::System.String value);
        partial void OnreviewContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numHelpful
        {
            get
            {
                return _numHelpful;
            }
            set
            {
                OnnumHelpfulChanging(value);
                ReportPropertyChanging("numHelpful");
                _numHelpful = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numHelpful");
                OnnumHelpfulChanged();
            }
        }
        private Nullable<global::System.Int32> _numHelpful;
        partial void OnnumHelpfulChanging(Nullable<global::System.Int32> value);
        partial void OnnumHelpfulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numTotal
        {
            get
            {
                return _numTotal;
            }
            set
            {
                OnnumTotalChanging(value);
                ReportPropertyChanging("numTotal");
                _numTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numTotal");
                OnnumTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _numTotal;
        partial void OnnumTotalChanging(Nullable<global::System.Int32> value);
        partial void OnnumTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numComments
        {
            get
            {
                return _numComments;
            }
            set
            {
                OnnumCommentsChanging(value);
                ReportPropertyChanging("numComments");
                _numComments = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numComments");
                OnnumCommentsChanged();
            }
        }
        private Nullable<global::System.Int32> _numComments;
        partial void OnnumCommentsChanging(Nullable<global::System.Int32> value);
        partial void OnnumCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewFor
        {
            get
            {
                return _reviewFor;
            }
            set
            {
                OnreviewForChanging(value);
                ReportPropertyChanging("reviewFor");
                _reviewFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewFor");
                OnreviewForChanged();
            }
        }
        private global::System.String _reviewFor;
        partial void OnreviewForChanging(global::System.String value);
        partial void OnreviewForChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewType
        {
            get
            {
                return _reviewType;
            }
            set
            {
                OnreviewTypeChanging(value);
                ReportPropertyChanging("reviewType");
                _reviewType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewType");
                OnreviewTypeChanged();
            }
        }
        private global::System.String _reviewType;
        partial void OnreviewTypeChanging(global::System.String value);
        partial void OnreviewTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> statsCollectedAt
        {
            get
            {
                return _statsCollectedAt;
            }
            set
            {
                OnstatsCollectedAtChanging(value);
                ReportPropertyChanging("statsCollectedAt");
                _statsCollectedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("statsCollectedAt");
                OnstatsCollectedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _statsCollectedAt;
        partial void OnstatsCollectedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnstatsCollectedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isAmazonVerifiedPurchase
        {
            get
            {
                return _isAmazonVerifiedPurchase;
            }
            set
            {
                OnisAmazonVerifiedPurchaseChanging(value);
                ReportPropertyChanging("isAmazonVerifiedPurchase");
                _isAmazonVerifiedPurchase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAmazonVerifiedPurchase");
                OnisAmazonVerifiedPurchaseChanged();
            }
        }
        private Nullable<global::System.Boolean> _isAmazonVerifiedPurchase;
        partial void OnisAmazonVerifiedPurchaseChanging(Nullable<global::System.Boolean> value);
        partial void OnisAmazonVerifiedPurchaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String format
        {
            get
            {
                return _format;
            }
            set
            {
                OnformatChanging(value);
                ReportPropertyChanging("format");
                _format = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("format");
                OnformatChanged();
            }
        }
        private global::System.String _format;
        partial void OnformatChanging(global::System.String value);
        partial void OnformatChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Review_Book", "Book")]
        public Book Book
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("AmazonCrawlerModel.FK_Review_Book", "Book").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("AmazonCrawlerModel.FK_Review_Book", "Book").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Book> BookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("AmazonCrawlerModel.FK_Review_Book", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Book>("AmazonCrawlerModel.FK_Review_Book", "Book", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Review_Reviewer", "Reviewer")]
        public Reviewer Reviewer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reviewer>("AmazonCrawlerModel.FK_Review_Reviewer", "Reviewer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reviewer>("AmazonCrawlerModel.FK_Review_Reviewer", "Reviewer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reviewer> ReviewerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reviewer>("AmazonCrawlerModel.FK_Review_Reviewer", "Reviewer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reviewer>("AmazonCrawlerModel.FK_Review_Reviewer", "Reviewer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmazonCrawlerModel", Name="Reviewer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reviewer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reviewer object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Reviewer CreateReviewer(global::System.String id)
        {
            Reviewer reviewer = new Reviewer();
            reviewer.id = id;
            return reviewer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewerName
        {
            get
            {
                return _reviewerName;
            }
            set
            {
                OnreviewerNameChanging(value);
                ReportPropertyChanging("reviewerName");
                _reviewerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewerName");
                OnreviewerNameChanged();
            }
        }
        private global::System.String _reviewerName;
        partial void OnreviewerNameChanging(global::System.String value);
        partial void OnreviewerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String profileURL
        {
            get
            {
                return _profileURL;
            }
            set
            {
                OnprofileURLChanging(value);
                ReportPropertyChanging("profileURL");
                _profileURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("profileURL");
                OnprofileURLChanged();
            }
        }
        private global::System.String _profileURL;
        partial void OnprofileURLChanging(global::System.String value);
        partial void OnprofileURLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_Review_Reviewer", "Review")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("AmazonCrawlerModel.FK_Review_Reviewer", "Review");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("AmazonCrawlerModel.FK_Review_Reviewer", "Review", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_ReviewerBadge_Reviewer", "ReviewerBadge")]
        public EntityCollection<ReviewerBadge> ReviewerBadges
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReviewerBadge>("AmazonCrawlerModel.FK_ReviewerBadge_Reviewer", "ReviewerBadge");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReviewerBadge>("AmazonCrawlerModel.FK_ReviewerBadge_Reviewer", "ReviewerBadge", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmazonCrawlerModel", Name="ReviewerBadge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReviewerBadge : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReviewerBadge object.
        /// </summary>
        /// <param name="reviewerId">Initial value of the reviewerId property.</param>
        /// <param name="badge">Initial value of the badge property.</param>
        /// <param name="statsCollectedAt">Initial value of the statsCollectedAt property.</param>
        public static ReviewerBadge CreateReviewerBadge(global::System.String reviewerId, global::System.String badge, global::System.DateTime statsCollectedAt)
        {
            ReviewerBadge reviewerBadge = new ReviewerBadge();
            reviewerBadge.reviewerId = reviewerId;
            reviewerBadge.badge = badge;
            reviewerBadge.statsCollectedAt = statsCollectedAt;
            return reviewerBadge;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String reviewerId
        {
            get
            {
                return _reviewerId;
            }
            set
            {
                if (_reviewerId != value)
                {
                    OnreviewerIdChanging(value);
                    ReportPropertyChanging("reviewerId");
                    _reviewerId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("reviewerId");
                    OnreviewerIdChanged();
                }
            }
        }
        private global::System.String _reviewerId;
        partial void OnreviewerIdChanging(global::System.String value);
        partial void OnreviewerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String badge
        {
            get
            {
                return _badge;
            }
            set
            {
                if (_badge != value)
                {
                    OnbadgeChanging(value);
                    ReportPropertyChanging("badge");
                    _badge = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("badge");
                    OnbadgeChanged();
                }
            }
        }
        private global::System.String _badge;
        partial void OnbadgeChanging(global::System.String value);
        partial void OnbadgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime statsCollectedAt
        {
            get
            {
                return _statsCollectedAt;
            }
            set
            {
                if (_statsCollectedAt != value)
                {
                    OnstatsCollectedAtChanging(value);
                    ReportPropertyChanging("statsCollectedAt");
                    _statsCollectedAt = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("statsCollectedAt");
                    OnstatsCollectedAtChanged();
                }
            }
        }
        private global::System.DateTime _statsCollectedAt;
        partial void OnstatsCollectedAtChanging(global::System.DateTime value);
        partial void OnstatsCollectedAtChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AmazonCrawlerModel", "FK_ReviewerBadge_Reviewer", "Reviewer")]
        public Reviewer Reviewer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reviewer>("AmazonCrawlerModel.FK_ReviewerBadge_Reviewer", "Reviewer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reviewer>("AmazonCrawlerModel.FK_ReviewerBadge_Reviewer", "Reviewer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reviewer> ReviewerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reviewer>("AmazonCrawlerModel.FK_ReviewerBadge_Reviewer", "Reviewer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reviewer>("AmazonCrawlerModel.FK_ReviewerBadge_Reviewer", "Reviewer", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
